movie_titles = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Matrix",
    "The Lord of the Rings: The Return of the King",
    "Interstellar",
    "The Empire Strikes Back",
    "Gladiator",
    "The Lion King",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "The Green Mile",
    "Avengers: Endgame",
    "Titanic",
    "The Prestige",
    "Schindler's List",
    "Back to the Future",
    "Whiplash",
    "Django Unchained",
    "Goodfellas",
    "The Social Network",
    "Toy Story",
    "The Departed",
    "WALL·E",
    "The Wolf of Wall Street",
    "Braveheart",
    "Jurassic Park",
    "Deadpool",
    "Shutter Island",
    "The Truman Show",
    "No Country for Old Men",
    "The Grand Budapest Hotel",
    "A Beautiful Mind",
    "Coco",
    "Up",
    "Inside Out",
    "The Imitation Game",
    "The Revenant",
    "Knives Out",
    "Parasite",
    "Joker",
    "The Avengers",
    "Iron Man",
    "Spider-Man: Into the Spider-Verse",
    "The Batman",
    "Doctor Strange",
    "Black Panther",
    "Tenet",
    "The Hateful Eight",
    "Catch Me If You Can",
    "The Pursuit of Happyness",
    "Life of Pi",
    "Slumdog Millionaire",
    "Her",
    "The Curious Case of Benjamin Button",
    "The Martian",
    "1917",
    "La La Land",
    "The Greatest Showman",
    "Bohemian Rhapsody",
    "The Big Short",
    "Birdman",
    "The Theory of Everything",
    "Gone Girl",
    "Arrival",
    "Blade Runner 2049",
    "Logan",
    "Prisoners",
    "The Conjuring",
    "It",
    "A Quiet Place",
    "Get Out",
    "Us",
    "Don't Look Up",
    "Everything Everywhere All at Once",
    "The Whale",
    "Oppenheimer",
    "Barbie",
    "The Super Mario Bros. Movie",
    "John Wick",
    "Mission: Impossible – Fallout",
    "Top Gun: Maverick",
    "The Hunger Games",
    "Harry Potter and the Sorcerer's Stone",
    "Fantastic Beasts and Where to Find Them",
    "Frozen",
    "Moana",
    "Zootopia",
    "Ratatouille",
    "Monsters, Inc.",
    "Finding Nemo",
    "The Incredibles",
    "Cars",
    "How to Train Your Dragon",
    "Kung Fu Panda",
    "Despicable Me",
    "Minions"
]
