services:
  - type: web
    name: ai-movie-guesser
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ODMB_API_KEY
        sync: false
